[package]
name = "storms-and-swords"
version = "0.1.0"
authors = ["tucker, mooman219"]

[dependencies]
gfx = "*"
gfx_app = "*"
image = "0.13.0"
glutin = "*"
glium = "0.16.0"
gfx_window_glutin = "*"
cgmath = "0.12.0"
threadpool = "1.3.2"
